### PR TITLE
Re-enable fcurves without a group, more PEP8 formatting/cleanup and etc

### PR DESCRIPTION
**Pull request by Irmitya**
The bulk of changes are just tweaks to how the code is written.
Functionally, the only difference here should be that
1) If an object doesn't have an action but the code still checks it, it won't result in an error
2) If an action's fcurve doesn't have a group, it can still be manipulated.

### CODE REVIEW

**Comment by aresdevo** [comment]
Ok, I'm back. 
Thanks for the help. I'm sure the code most be better, but I will check to see what the changes are.

**Comment by aresdevo** [comment]
I love all the ways you made my code better. The points I mention above are the only things I need to solve before merging it. Thanks a lot for your help.

**Comment by Irmitya** [comment]
I didn't do it here, to keep things as much as how they were as possible but there's a thing you should know about calling functions that need `context`, from an operator. 

The TL;DR version is 
that you should always include `context` as an arg for functions, when you need to call it, and not use `bpy.context`
_(unless you're 100% positive it's a variable that would never change, and if it did, you would need the original, like bpy.context.preferences)_

- - - - -

When something calls an operator _`bpy.ops.op.idname()`_, you have the option to tweak the _"context"_ used in the operator's functions. 
This is similar to the UILayout's `layout.context_pointer_set('name', data_block)` function, except you're not limited to using any particular type of data.

In the operator's function `def execute(self, context)` generally you use the provided context variable because it's easier to type but it actually has a function. 

For example, `context.selected_pose_bones` normally gives you the exact same thing as `bpy.context.selected_pose_bones`. 
However, if someone wanted to run the operator but without having to manually change what's selected beforehand, they'd replace the operator's context with a `context.copy()`.

This is generally done like:
```
context_copy = context.copy()
context_copy['selected_pose_bones'] = ["list of alternative bones"]
context_copy['new_var'] = any  # just a variable that doesn't exist
bpy.ops.op.idname(context_copy)
```

Then, when calling `context.selected_pose_bones`, it will give you what was specified in `context_copy`, instead of what's actually selected.

Additionally, it may be a bug somewhere internally but at times, `bpy.context` doesn't give you the list of variables it normally has, so when calling it, it doesn't find the correct variables it **_should_** have.
It's related to the bpy.context from the "addon.py" file being momentarily different from the bpy.context from the "blender.exe".
This notably happens when using a function in `threading.Timer()` and I believe `bpy.app.timers` but it probably happens elsewhere too _(note: the function has to be running; the code that calls `bpy.context`, does not)_.

What definitely fixes this is using the context from the operator, as an arg sent directly to the function.

**Comment by aresdevo** [comment]
Thanks for all that info, I will keep that in mind. I will merge your code and deal with the things I mentioned latter

**Pull request merged**
